### ISSUE TITLE
translation failure

### ISSUE THREAD

**Issue by 3052** [PouleR/spotify-login#7]
I tried translating this code into another language, but my login request fails for some reason. for the first request, the request body is 70 bytes with the PHP code here and my code as well. also the request seems to be identical for both:

~~~
2024-03-03 09:41:20 POST https://login5.spotify.com/v3/login HTTP/2.0
content-type:     application/x-protobuf
accept:           */*
user-agent:       Symfony HttpClient (Curl)
accept-encoding:  gzip
content-length:   70

[message]    1
[string]     1.1    9a8d2f0ce77a4e248bb71fefcb557637
[message]    101
[string]     101.1  EMAIL
[string]     101.2  PASSWORD
~~~

for the second request, request body is 321 bytes with the PHP code here and my code as well. request again seems to be identical for both, other than the loginContext and prefix returned from the server:

~~~
2024-03-03 09:41:43 POST https://login5.spotify.com/v3/login HTTP/2.0
content-type:     application/x-protobuf
accept:           */*
accept-encoding:  identity
user-agent:       Symfony HttpClient (Curl)
content-length:   321

[message]    1
[string]     1.1      9a8d2f0ce77a4e248bb71fefcb557637
[bytes]      2        b".i\x1d\x00\x00\x00\x00\x00\x00\x04\xdb\xd8+\xbc\x06\x04\x07\xad\xd0\xfeSi\x91\xa6u\xadH\x18Y\xfd\x87\xe8\xb5\xbbWP1Y\x89m\xcdn!W\xa9/X7T\x02\xa1C\xa232|n\xa4(\xdf\xfd\xe4\xfd\xbc\xa8G\x85\xa21u\x15\x04\x88\xc9\x8dX\x0b\xef:\x82\xff\xc0\x18q\t\xceM\x846\xd6\nvd\x1e\x1bb?\xaa\xd9\n\x154\x89P\xbb\xf0\xc7\x8d71\x01vlJ\x8cT|\x9a\xc8\xa8>\x9b\x81\x9a/\xf2\xbc\xafw\x86\xb1(\xa6\xd2mK\xad\x1f?\x8d\xc6\t \xc0W\xf7\x16\x99\xd1Z)\xd0[A}\x1a>)\x9cC\xe0\x00\xa6\xdb<\x9d\x1a\x16\xc6f\x89\x892>h\xc6&\xcbi\xbf\x94\xa0\x0e\x032'R)e\xfc\xd3.\x8aO$\xb6\xc9\xe1\xab\xbd\xa6n'\x97!\xfb>\x1e\xc6?%*\xa6\x99\x11\xb2\xf5\xec\x90\xd0\x83g\xa0r"
[message]    3
[message]    3.1
[message]    3.1.1
[bytes]      3.1.1.1  b'\xbc\x80\xbe\x07\xbb.i\x1d\x00\x00\x00\x00\x00\x00\x04\xdb'
[message]    101
[string]     101.1    EMAIL
[string]     101.2    PASSWORD
~~~

I also tried using `solveChallenge` by itself to compare against my code, and it seems my code is returning the correct suffix values. do you know why my requests might be failing? Is Spotify using TLS fingerprinting or something?

**Comment by 3052** [comment]
figured it out - my function was accidentally modifying the prefix value

**Comment by PouleR** [comment]
Good to hear! You can always look at the original implementation here: https://github.com/librespot-org/librespot-java/tree/dev/lib/src/main/proto/spotify/login5/v3 (in Java)
